---

- name: Deploy Dolibarr database
  hosts: dolidb
  roles:
    - role: mysql
      become: yes

- name: Deploy Dolibarr instance
  hosts: dolinstance
  roles:
    - role: debian_repos
      become: yes
    - role: apache2
      become: yes
    - role: php
      become: yes
    - role: dolibarr
      become: yes
