---

- name: Install Debian repositories
  apt_repository:
    repo: "{{ item.repo }}"
    state: present
  with_items: "{{ debian_repositories }}"

- name: Install Debian repositories keys
  apt_key:
    url: "{{ item.key }}"
    state: present
  with_items: "{{ debian_repositories }}"

- name: Update apt-cache
  command: apt-get update